GET http://admin:123456@127.0.0.1:5984/_all_dbs

###
GET http://admin:123456@127.0.0.1:5984/utenti/_all_docs

###
GET http://admin:123456@127.0.0.1:5984/commenti/_design/all/_view/_viewù

###
GET https://localhost/commenti/lista_commenti/ale

###
PUT http://admin:123456@127.0.0.1:5984/commenti
content-type: application/json

{
    "name": "Alessia",
    "surname": "Angelone"
}

###
POST http://admin:123456@127.0.0.1:5984/utenti/_view/all
content-type: application/json

###
PUT http://admin:123456@127.0.0.1:5984/primopiano

###
GET http://admin:123456@127.0.0.1:5984/primopiano

###
DELETE http://admin:123456@127.0.0.1:5984/primopiano