name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./containers/node
    steps:
      - uses: actions/checkout@v3
      - name: start docker
        run: docker-compose up -d
      - name: docker ps
        run: docker ps -a
      - name: test connection nginx
        run: docker run --network container:nginx appropriate/curl http://localhost/
      - name: npm test
        run: npm i mocha -g && npm i && npm test
